import { StyleSheet } from 'react-native';

export const actionStyles = StyleSheet.create({
  actionCard: {
    backgroundColor: '#1C1C23',
    borderRadius: 28,
    padding: 24,
    marginBottom: 24,
    elevation: 4,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: '#2D2D37',
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#E8E8F0',
    marginBottom: 20,
    letterSpacing: -0.5,
  },
  inputContainer: {
    marginBottom: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: '#2D2D37',
    borderRadius: 16,
    padding: 16,
    fontSize: 16,
    backgroundColor: '#252530',
    color: '#E8E8F0',
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  addButton: {
    flex: 1,
    backgroundColor: '#6EDB74',
    borderRadius: 20,
    paddingVertical: 16,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#6EDB74',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  spendButton: {
    flex: 1,
    backgroundColor: '#FF6B6B',
    borderRadius: 20,
    paddingVertical: 16,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#FF6B6B',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.1,
  },
});