import { StyleSheet } from 'react-native';

export const screenStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: '#0F0F14',
  },
  recentTransactions: {
    backgroundColor: '#1C1C23',
    borderRadius: 28,
    padding: 24,
    marginBottom: 16,
    elevation: 4,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#E8E8F0',
    marginBottom: 20,
    letterSpacing: -0.5,
  },
  viewAllButton: {
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#2D2D37',
    borderRadius: 20,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#6366F1',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  viewAllText: {
    color: '#A5A6FF',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.1,
  },
  transactionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#2D2D37',
  },
  transactionCount: {
    fontSize: 14,
    color: '#8B8B95',
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  transactionWrapper: {
    backgroundColor: '#252530',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 4,
    marginBottom: 12,
    elevation: 3,
    shadowColor: '#6366F1',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    borderWidth: 1,
    borderColor: '#2D2D37',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 48,
    paddingHorizontal: 32,
    backgroundColor: '#1C1C23',
    borderRadius: 28,
    elevation: 2,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: '#2D2D37',
  },
  emptyText: {
    fontSize: 16,
    color: '#8B8B95',
    textAlign: 'center',
    lineHeight: 24,
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  cardHighlight: {
    backgroundColor: '#6366F1',
    borderRadius: 16,
    padding: 16,
    elevation: 3,
    shadowColor: '#6366F1',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  primaryText: {
    color: '#E8E8F0',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: -0.2,
  },
  secondaryText: {
    color: '#B8B8C0',
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  accentColor: {
    color: '#A5A6FF',
  },
  surfaceVariant: {
    backgroundColor: '#2D2D37',
  },
});